"coauthors":
  - changed-files:
      - any-glob-to-any-file: ["packages/coauthors/**/*"]
"@coauthors/core":
  - changed-files:
      - any-glob-to-any-file: ["packages/core/**/*"]
"@coauthors/cli":
  - changed-files:
      - any-glob-to-any-file: ["packages/cli/**/*"]
"@coauthors/vscode":
  - changed-files:
      - any-glob-to-any-file: ["packages/vscode/**/*"]
"coauthors.vercel.app":
  - changed-files:
      - any-glob-to-any-file: ["docs/coauthors.vercel.app/**/*"]
"dependencies":
  - changed-files:
      - any-glob-to-any-file: ["pnpm-lock.yaml"]
