coverage:
  status:
    patch: off
    project:
      default:
        target: 100%
        threshold: 60%

comment:
  layout: 'header, reach, diff, flags, components'

ignore:
  - '**/*.test-d.*'

component_management:
  individual_components:
    - component_id: core
      name: '@coauthors/core'
      paths:
        - packages/core/**
    - component_id: cli
      name: '@coauthors/cli'
      paths:
        - packages/cli/**
    - component_id: prepare-commit-msg
      name: '@coauthors/prepare-commit-msg'
      paths:
        - packages/prepare-commit-msg/**
    - component_id: vscode
      name: '@coauthors/vscode'
      paths:
        - packages/vscode/**
