name: Lint Commenter

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-commenter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile
      - run: pnpm ci:eslint || exit 1
      - if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Check. Please run `pnpm ci:eslint -- --fix` to fix eslint error."
            })
